/**** 
Tue May  3 15:26:07 EDT 2016 
venkat@venkat

desc: this is a SQL equivalent - not optimized - just tested in dtdev
      of the corresponding kettle transformation with the same name.
      tested in dtdev
********/

-- ## captures Get PatientID's input connector in ktr
CREATE TABLE VENKAT.T01 AS (
SELECT 
    /*+ PARALLEL 4 */ 
    P.PATIENT_ID,
    P.MPI_EUID,
    SYSDATE MYDATE
FROM CDW.PATIENT@DTPRD2LINK P
INNER JOIN VENKAT.CDW_PATIENT_TMP_20160320 P2 ON (P.MPI_EUID = P2.MPI_EUID)
);

-- ## captures "Join MPI Enterprise for ID's and Lookup Datasource
CREATE TABLE VENKAT.T02 AS (
SELECT DISTINCT
    E.EUID,
    E.LID AS MPI_LID,
    E.SYSTEMCODE AS MPI_SYSTEMCODE,
  F.DATASOURCE_ID
FROM PATIENT.SBYN_ENTERPRISE@MPIPRDLINK E, CDW.DATASOURCE F
WHERE E.EUID IN (SELECT MPI_EUID FROM VENKAT.T01) AND
(F.DATASOURCE_NAME = E.SYSTEMCODE) 
)
;


/*********** DDL below is ONLY FOR COMPLETENESS, DO NOT USE ********** -- BEGIN */

--------------------------------------------------------
--  DDL for Table PATIENT_ID_MAP
--------------------------------------------------------

  CREATE TABLE "VENKAT"."PATIENT_ID_MAP" 
   (    "PATIENT_ID" NUMBER(22,0), 
    "MPI_EUID" VARCHAR2(25 BYTE), 
    "MPI_LID" VARCHAR2(25 BYTE), 
    "MPI_SYSTEMCODE" VARCHAR2(50 BYTE), 
    "STATUS" VARCHAR2(50 BYTE), 
    "LAST_UPDATE_DATE" DATE DEFAULT sysdate, 
    "DATASOURCE_ID" NUMBER(22,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" 
  PARALLEL 4 ;
--------------------------------------------------------
--  DDL for Index PATIENT_ID_MAP_IDX1
--------------------------------------------------------

  CREATE INDEX "VENKAT"."PATIENT_ID_MAP_IDX1" ON "VENKAT"."PATIENT_ID_MAP" ("MPI_LID", "MPI_SYSTEMCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;
--------------------------------------------------------
--  DDL for Index PATIENTIDMAP_TEMP
--------------------------------------------------------

  CREATE INDEX "VENKAT"."PATIENTIDMAP_TEMP" ON "VENKAT"."PATIENT_ID_MAP" ("PATIENT_ID", "MPI_EUID", "MPI_SYSTEMCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;
--------------------------------------------------------
--  DDL for Index PK_PATIENT_ID_MAP
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENKAT"."PK_PATIENT_ID_MAP" ON "VENKAT"."PATIENT_ID_MAP" ("PATIENT_ID", "MPI_EUID", "MPI_LID", "MPI_SYSTEMCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;
--------------------------------------------------------
--  Constraints for Table PATIENT_ID_MAP
--------------------------------------------------------

  ALTER TABLE "VENKAT"."PATIENT_ID_MAP" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "VENKAT"."PATIENT_ID_MAP" MODIFY ("MPI_EUID" NOT NULL ENABLE);
  ALTER TABLE "VENKAT"."PATIENT_ID_MAP" MODIFY ("MPI_LID" NOT NULL ENABLE);
  ALTER TABLE "VENKAT"."PATIENT_ID_MAP" MODIFY ("LAST_UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "VENKAT"."PATIENT_ID_MAP" ADD CONSTRAINT "PK_PATIENT_ID_MAP" PRIMARY KEY ("PATIENT_ID", "MPI_EUID", "MPI_LID", "MPI_SYSTEMCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01"  ENABLE;


/*********** DDL above is ONLY FOR COMPLETENESS, DO NOT USE ********** -- END*/




-- ## this captures the Merge incremental into PIM process

merge into venkat.patient_id_map pim
using (
 select
    T1.patient_id,
    T1.mpi_euid,
    T2.MPI_lid,
    T2.MPI_systemcode,
    T2.datasource_id,
    sysdate last_update_date
  from VENKAT.T01 T1, VENKAT.T02 T2
) incr
on (incr.mpi_lid = pim.mpi_lid and incr.mpi_systemcode = pim.mpi_systemcode)
when matched then update set
  pim.PATIENT_ID = incr.PATIENT_ID,
  pim.MPI_EUID = incr.MPI_EUID,
  pim.DATASOURCE_ID = incr.DATASOURCE_ID,
  pim.LAST_UPDATE_DATE = incr.LAST_UPDATE_DATE
when not matched then insert (
  pim.PATIENT_ID,
  pim.MPI_EUID,
  pim.MPI_LID,
  pim.MPI_SYSTEMCODE,
  pim.DATASOURCE_ID,
  pim.LAST_UPDATE_DATE
) values (
  incr.PATIENT_ID,
  incr.MPI_EUID,
  incr.MPI_LID,
  incr.MPI_SYSTEMCODE,
  incr.DATASOURCE_ID,
  incr.LAST_UPDATE_DATE
)
;

