
  CREATE TABLE "USERNAME"."RXNORM_LOOKUP" 
   (	"ORDER_RXCUI" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"INGRED_RXCUI" VARCHAR2(10 BYTE), 
	"INGRED_DESC" VARCHAR2(200 BYTE), 
	 CONSTRAINT "LOOKUP_PK" PRIMARY KEY ("ORDER_RXCUI", "INGRED_RXCUI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;